"""Add avatar_url in User

Revision ID: 090156ce6083
Revises: 6485505ad480
Create Date: 2026-02-07 21:21:52.507493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "090156ce6083"
down_revision: Union[str, Sequence[str], None] = "6485505ad480"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("avatar_url", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "avatar_url")
    # ### end Alembic commands ###
