"""Add media model

Revision ID: 8b180f0b5829
Revises: be6c7b09111e
Create Date: 2026-01-31 16:28:35.710042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "8b180f0b5829"
down_revision: Union[str, Sequence[str], None] = "be6c7b09111e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("media_type", sa.Enum("IMAGE", "VIDEO", name="type"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="status"),
            nullable=False,
        ),
        sa.Column("s3_key", sa.String(length=500), nullable=False),
        sa.Column("s3_bucket", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("user_tags", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("media_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("media_pkey")),
        sa.UniqueConstraint("s3_key", name=op.f("media_s3_key_key")),
    )
    op.create_index(op.f("media_media_type_idx"), "media", ["media_type"], unique=False)
    op.create_index(op.f("media_status_idx"), "media", ["status"], unique=False)
    op.create_index(op.f("media_user_id_idx"), "media", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("media_user_id_idx"), table_name="media")
    op.drop_index(op.f("media_status_idx"), table_name="media")
    op.drop_index(op.f("media_media_type_idx"), table_name="media")
    op.drop_table("media")
    # ### end Alembic commands ###
