"""Add has_password field in User

Revision ID: 6485505ad480
Revises: 8b180f0b5829
Create Date: 2026-02-07 21:07:54.140578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6485505ad480"
down_revision: Union[str, Sequence[str], None] = "8b180f0b5829"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "has_password", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "has_password")
    # ### end Alembic commands ###
